apiVersion: v1
description: A Helm chart for installing Gluster on Kubernetes. After the installation gluster-heketi-config config map and gluster-heketi pod have to be removed
maintainers:
- name: Boris Lublinsky
name: glusterkuberneteschart
version: 0.1.0
