# Default values for gluster on kubernetes install.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# docker images
image:
  gluster: lightbend/gluster_heketi
  pullPolicy: Always
# Kubectl
kubectl:
  apiserver: kube-apiserver-0-instance.kubernetes.mesos

# Gluster topology
topology:
  definition: >
    {
    "clusters": [
      {
      "nodes": [
        {
          "node": {
            "hostnames": {
              "manage": [
                "<node-1-name>"
              ],
              "storage": [
                "<node-1-ip>"
              ]
            },
            "zone": 1
          },
          "devices": [
            "/dev/<node-1-disk>"
          ]
        },
        {
          "node": {
            "hostnames": {
              "manage": [
                "<node-2-name>"
              ],
              "storage": [
                "<node-2-ip>"
              ]
            },
            "zone": 1
          },
          "devices": [
            "/dev/<node-2-disk>"
          ]
        },
        {
          "node": {
            "hostnames": {
              "manage": [
                "<node-3-name>"
              ],
              "storage": [
                "<node-3-ip>"
              ]
            },
            "zone": 1
          },
          "devices": [
            "/dev/<node-3-disk>"
          ]
        }
      ]
    }
    ]
    }